# AppVeyor build configuration

branches:
  except:
  - master

environment:
  matrix:
   - platform: x86
   - platform: x64

# Build script
build_script:
- powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1 -Platform %platform%

# Publish artifacts (installer)
artifacts:
 - path: build-%platform%/Release/PicoTorrent-*-%platform%.exe

test: off
