# AppVeyor build configuration

os: Visual Studio 2019

environment:
  global:
    BOOST_ROOT: C:\Libraries\boost_1_71_0

  matrix:
   - platform: x86
     CMAKE_PREFIX_PATH: C:\Qt\5.13.1\msvc2017
     OPENSSL_ROOT_DIR: C:\OpenSSL-v111-Win32

   - platform: x64
     CMAKE_PREFIX_PATH: C:\Qt\5.13.1\msvc2017_64
     OPENSSL_ROOT_DIR: C:\OpenSSL-v111-Win64

# Build script
build_script:
- git submodule update --init --recursive
- powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1 -Platform %platform%

# Publish artifacts
artifacts:
 - path: build-*/Release/packages/PicoTorrent-*-*.appx
 - path: build-*/Release/packages/PicoTorrent-*-*.exe
 - path: build-*/Release/packages/PicoTorrent-*-*.zip

test: off
